spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cerberus
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health